### ISSUE TITLE
Support go-redis v8

### ISSUE THREAD

**Issue by kpurdon** [rbcervilla/redisstore#5]
I'm more than happy to do the actual work to release a `v2` here that supports `go-redis` v8 (https://pkg.go.dev/github.com/go-redis/redis/v8) but wanted to check to make sure nothing was actively being worked on and that a v2 release here is possible.

Additionally, it would be great to know how you want to support major version upgrades w/ `go-redis`. I could either see `/v2` here that uses `go-redis` `/v8`, or a `/v8` here and starting to maintain major version parody w/ `go-redis` (maybe even another `/v7` here to support all possible major versions if needed.

Thanks!

**Comment by kpurdon** [comment]
Hi @rbcervilla any thoughts on this? Thanks!

**Comment by rbcervilla** [comment]
Hi @kpurdon, I pushed [v8 branch](https://github.com/rbcervilla/redisstore/tree/v8) and I published [v8.0.0-rc1](https://github.com/rbcervilla/redisstore/releases/tag/v8.0.0-rc1). Would you like to take a look?
I'm going to test it before merge into master and release v8.0.0

Thanks!

**Comment by kpurdon** [comment]
@rbcervilla awesome, I'll test this on my side this morning.

Of note, since this is a major version release you can just add `ctx context.Context` to `NewRedisStore` instead of creating the `NewRedisStoreWithContext`. This will force people who upgrade to the major version to pass a real context instead of inheriting a `context.TODO` silently.

**Comment by kpurdon** [comment]
Everything is looking good on my side after the upgrade. Let me know if you'd like me to do any additional testing.

**Comment by rbcervilla** [comment]
You're right. It's better to force `ctx context.Context` on `NewRedisStore`. I changed it and tested and I think it's ok. I just released v8.0.0 on master.

Thanks so much!
