### ISSUE TITLE
How do I set session secrete key?

### ISSUE THREAD

**Issue by windroldev** [rbcervilla/redisstore#9]
I'm really sorry.. I'm a beginner and when I watched the tutorial on YouTube working with gollira session there was a part for specifying the secret key of the session. Using your library seems to bring this question on mind just for curiosity. Could please explain it to me if not teaching.

**Comment by rbcervilla** [comment]
Hello, this store doesn't implement secure cookie because is not necessary. You can take a look at this [issue](https://github.com/rbcervilla/redisstore/issues/1#issuecomment-568788137) where I explain why it is not necessary.
